name: 'min_dbt'
version: '0.1.0'
config-version: 2

profile: default

model-paths: ["models"]
analysis-paths: []
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: [macros"]
snapshot-paths: []

clean-targets:
  - "target"
  - "dbt_packages"
